name: MasterDeployCI
on:
  push:
    branches:
      - development
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Packages
      run: npm install
    - name: Deploy to GH Pages
      run: |
        git config --global user.email "nobak.dev@gmail.com"
        git config --global user.name "nobakent"
        git remote set-url origin https://81a4179ab4ef4dfaab130513176fe7da6bda91a9@github.com/your_github_username>/your_repo>.git
        npm run deploy
